Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
  File "NetworkThreads.pyc", line 87, in runSerial
  File "serial\serialwin32.pyc", line 31, in __init__
  File "serial\serialutil.pyc", line 240, in __init__
  File "serial\serialwin32.pyc", line 62, in open
SerialException: could not open port 'COM6': WindowsError(2, 'El sistema no puede encontrar el archivo especificado.')

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
  File "NetworkThreads.pyc", line 87, in runSerial
  File "serial\serialwin32.pyc", line 31, in __init__
  File "serial\serialutil.pyc", line 240, in __init__
  File "serial\serialwin32.pyc", line 62, in open
SerialException: could not open port 'COM6': WindowsError(2, 'El sistema no puede encontrar el archivo especificado.')

